services:
  redis:
    image: redis:alpine
    container_name: flash_sale_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: flash_sale_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:alpine
    container_name: flash_sale_postgres
    environment:
      POSTGRES_DB: flash_sale
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
