spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flash_sale
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      repositories:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  stock:
    item-id: 1
    quantity: 10
  rabbitmq:
    exchange: flashSaleExchangeV2
    queue: flashSaleQueueV2
    routing-key: flash.sale.routing.key
    dead-letter-exchange: flashSaleDlqExchangeV2
    dead-letter-routing-key: flash.sale.dlq
